const CACHE = 'analyseur-v3';

// Icons as base64 — served with correct image/png content-type
const ICON_192_B64 = 'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAIAAADdvvtQAAACb0lEQVR42u3ZwZXDIAxAQTeQctL/NeUkHaQFWxgjpPlv78tDczDK8ZIGOlyBABJAAkgASQAJIAEkgCSABJAAEkASQAJIAAkgCSABJIAEkACSABJAAkgASQAJIAEkgCSABJAAEkASQAJIAAkgASQBJIAEkABS2j6/9/gfQABl0QMQQAABBJAeMwQQQIn0ANTIkGe8hgwBpLiheccAqLih2WcAqCyjZ/47QI3e8H7KAAggASSAAAIIIIAAEkACSAABBBBAAkgACSCAAAJIAAkgAQQQQAAJIAEkgAACCCCAADLX63MFCCCABBBAAAFUypCPaIAA0iJDnvEaGjBAig/YIlHBMWd+7gGU3VDyfQFASSXtsnACyCIRIIAAAgggAQQQQAABBBBAAAkggAACCCCAAAJIAAEEEEAAAQQQQAABJIAAAggggAAyV4AYAggggAACCCCAAOpoyCsMIIAAWmTIHgig+NVbJAIUv30bS4CCM7DyBujy4DMsCwCquQQ6eeMAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQADtB2ijuQIEEEAAAQTQvXfhGwgggABaBMgrDKCh6wAIoPiN2AMBFL8Ui0SA4vdiEw1Q8Hb8lAGQRSJAAAEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAAEEEEAASQAJIAEkgCSABND3dA4P0NAMUk1i02MDtHgke50WoESD2eWcAKUbT/4TeoXdM6SceYVh1IVOkT0QOgD1ZWSR2O4rm5vigOaNGZ1GgASQABJAEkACSAAJIAkgASSAVKQ/xgGDMpAav6kAAAAASUVORK5CYII=';
const ICON_512_B64 = 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAALy0lEQVR42u3bwRHiSBBFQTnQ5sj/K+aAB7igAyHR9TJjHZgPXW+CiT0WAEmHCQAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABAEAAABAAAAQAAAEAQAAAEABgA6/Puel/AgAgAAIAIAACADC+AQIAIAACAJAJwNTPQgAAARAAAAEQAAANEACAdAAGfxACAAiAAABogAAACMDs6y8AgAAIAIAGlK6/AAACIAAAGlC6/gIAaED0+gsAIAACAKABpesvAIAGRK+/AAAaEL3+AgBoQPT6CwCgAdHrLwCABpzZqQUA6GYgPrIAANEGWFgAgFwGrCoAQC4DlhQAoFUCuwkAEIqBfQQA2P7v7/4nYQEABEAABAAQAAEQAEAABEAAAAEQAAEABEAABAAQAAEQAEAABEAAAAEQAN9IQAAEAEAABABAAAQAQAAEAEAABABAAAQAQAAEAEAABABAAAQAQAAEABAAARAAQAAEQAAAARAAAQAEQAAEABAAARAAQAAEQAAAARAAAQAEQAAEABAAARAAQAAEQAAAARAAAQAEQAAEABAAARAAQAAEAEAABABAAAQAQAAEAEAABABAAAQAQAAEAEAABABAAAQAQAAEAEAABAAQAAEQAEAABEAAAAEQAAEABEAABAAQAAEQAEAABEAAAAEQAAEABEAABAAQAAEQAEAABEAAAAEQAAEABEAABAAQAAEAEAABABAAAQAQAAEAEAABABAAAQAcO5sIAODY2UQAAMfOJgIAAuDSCYAAgAa4dAIgACAAAmAWAQABEACzCAAIgAAIgACAAAiAAAgAaMC0MycAAgACIAACIAAgAAJgGQEADRh/4wRAAEAABEAABAA0oHTgBEAAQAAEQAAEADSgdN0EQABAAKKnTQAEADRAAARAAEADSndNAAQANCB61ARAAEADohdNAAQAWM1zJgACADx5Df38JQACAMUG+O1LAAQAig2I//AlAAIAxQzEf/USAAGAYgbiP3kJgABAMQPx37sEQAAgl4HyL10CIABQjEH2Ny4BEABw7DY4djYRABAAAbCJAIAACIAACAAIgAAIgACAAAiAAAgACIAACIAAgAAIgAAIAAiAAAiAAIAACIAACAAIgAAIgACAAAiAAAgACIAACIAAgAAIgAAIAAiAAAgA4NgJgAAAjp0ACADg2NlEAADHziYCADh2NhEAwLGziQAAjp1NBABw7GwiACAAjp1NBAAEwLGziQCAAAiATQQABEAAbCIAIAACIAACAAIgAAIgACAAAiAAAgACIAACIAAgAAIgAAIAAiAAAiAAIAACIAACAAIgAAIgACAAAiAAAgACIAACIAAgAAIgAAIAAiAAAgA4dgIgAIBjZxMBABw7mwgA4NjZRAAAx84mAgA4djYRAMCxs4kAAI6dTQQABMCxs4kAgAAIgE0EAARAAGwiACAAAiAAAgACIAACIAA4dgNetWNnEwFAAATALDYRAARAAATAJgKAAAiAANhEABAAARAAARAANEAABEAABAABEAABEAABQAAEQAAEQAAQgH2etGNnEwFAAATAMjYRADRAAATAJgKAAIx/z46dTQQADRAAx84mAoAAlB6zY2cTAUADBMCxs4kAIACll+zY2UQA0AABcOxsIgAIQOkZO3Y2EQA0IPqGHTubCAAaIACOnU0EAA0oPWDHziYCgAZEX69jZxMBgNV8uo6dTQQAnnz5fv4SAAEQAIoN8NuXAAiAAJBrgB++BEAABIBiBuK/egmAAAgAxQzEf/ISAAEQAIoZKP/eJQACIAAUM1D+pUsABEAAyPWg/BuXAAiAAODYOXY2EQABQAAcO5sIgAAgAI6dTQRAABAAx84mAiAACIBjZxMBEAA8bMfOJgIgAHjYjp1NBAA8bJvYRADAw7aJTQQAPGyb2EQAwMO2iU0EADxsm9hEAMDDtolNBAA8bJvYRAAQAA/bJjYRAATAsbOJTQQAAXDsbGITAUAAHDub2EQAEADHziY2EQAEwLGziQAIAALg2NlEAAQAAXDsbCIAAoAAOHY2EQABQAAcO5sIgAAgAI6dTQRAABAAx84mAiAACIBjZxMBEAAEwLGziQAIAALg2NlEAAQAD9uxs4kACAAetmNnEwEAD9smNhEA8LBtYhMBAA/bJjYRAPCwbWITAQAP2yY2EQDwsG1iEwFAADxsm9hEABAAD9smNhEABMCxs4lNBAABcOxsYhMBQAAcO5vYRAAQAMfOJgIgAAiAY2cTARAABMCxs4kACAAC4NjZRAAEAAFw7GwiAAKAADh2NhEAAUAAHDubCIAAIACOnU0EQAAQAMfOJgIgAL7Ed3yDPWyb2EQABEAAzGITmwiAAAiAY2cTmwiAAAiAY2cTmwiAAAiAY2cTmwiAAAiAY2cTz0cANEAAHDubCIAACMCWX18P2yY2EQABEADL2MQmAiAAAuDY2cQmAqABAuDY2cQmAiAAM7+7HrZNbCIAAiAAHrZNbCIAGlD64nrYNrGJAAiAAHjYNrGJAGhA6VvrYdvEJgKgAQLgYdvEJgIgAKWvrIdtE5sIgAZEv68etk1sIgAaEP2yetg2sYkAaIAAeNg2sYkAaEDpm+ph28QmAsBqfk09bJvYRAB48lvu5y/HziYCIAC5Bvjty7GziQAIQLEBfvhy7GwiAAKQy4BfvRw7mwiAABQz4J89HDubCIAAtDLg3zwcO5sIgADkSuAfPBw7mwiAAFRi4J86HDubCIAAOHb//g32sG1iEwEQAAEwi01sIgACIACOnU1sIgACIACOnU1sIgACIACOnU1sIgACIACOnU08HwEQAAFw7GwiAAIgAALg2NlEAARAAATAsbOJAAiAAAiAY2cTARAAARAAx84mAiAAAiAAjp1NBEAABEAAHDubCIAACIAAOHY2EQAB8CUWAMfOJgIgAL7ENnHsbCIAAiAANnHsbCIAAiAAHrZNbCIACICHbRObCAAC4GHbxCYCgAB42DaxiQAgAB62TWwiAALgG+xh28QmAiAAvsEetk1sIgACIABmsYlNBEAABMAsNrGJAAiAADh2NrGJAAiAADh2NrGJAAiAADh2NrGJAAiAADh2NhEAARAAAXDsbCIAAiAAAuDY2UQABEAABMCxs4kACIAACIBjZxMBEAABEADHziYCIAACIACOnU0EQAAAEAAABAAAAQBAAAAEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAH7sfQs7+wIgAETfv0Pgc0cAqB8C58AnjgCQPgeOgs8aASB9FJwGnzICQPo0uBE+XASA+o1wKXysCADpS+Fe+EARANL3wtXwUSIApK+G2+FDRABI3w5HxGeHAFA/Ik6JTw0BIH1K4gfF54UA4KbkzoqPCQHAfcHpRwCQAZx+BAAlwN1HAJABnH4EABnA6UcAkAGcfgQAJcDdRwCQAZx+BAAZwOlHAJABnH4EABlw+kEAKJTACO4+AoAL6A8OAoBr6A8LAkAwA1eOox/6EQDI/R3Z3UcAIJcBpx8BgOjvQk4/AgAy4PQjACADTj8CAErg7iMAIANOPwIAMuD0IwAgA04/AgBK4O4jACADTj8CADLg9CMAIANOPwIAyQz4iBEAaJXAB4oAQC4DPkQEAAABAEAAABAAAAQAAAEAQAAAEAAABAAAAQBAAAAQAAAEAAABABAAEwA0fQEB1EraN02JewAAAABJRU5ErkJggg==';

function b64toBlob(b64, type) {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return new Response(bytes, { headers: { 'Content-Type': type } });
}

const ASSETS = [
  './',
  './index.html',
  './manifest.json',
  'https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js',
  'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.min.js'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).catch(() => {}));
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys =>
    Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
  ));
  self.clients.claim();
});

self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);

  // Intercept icon requests — serve with proper image/png content-type
  if (url.pathname.endsWith('icon-192.png')) {
    e.respondWith(b64toBlob(ICON_192_B64, 'image/png'));
    return;
  }
  if (url.pathname.endsWith('icon-512.png')) {
    e.respondWith(b64toBlob(ICON_512_B64, 'image/png'));
    return;
  }

  // Share target POST
  if (e.request.method === 'POST' && url.pathname.includes('/analytics/')) {
    e.respondWith((async () => {
      const data = await e.request.formData();
      const file = data.get('file');
      const clients = await self.clients.matchAll();
      if (clients[0] && file) clients[0].postMessage({ type: 'shared-file', file });
      return Response.redirect('/analytics/', 303);
    })());
    return;
  }

  // Cache-first for everything else
  e.respondWith(
    caches.match(e.request).then(cached => {
      if (cached) return cached;
      return fetch(e.request).then(res => {
        if (res && res.status === 200 && e.request.method === 'GET') {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
        }
        return res;
      }).catch(() => cached || new Response('Offline', { status: 503 }));
    })
  );
});
