const CACHE = 'analyseur-v4';

// PNG icons embedded — served with correct Content-Type: image/png
const ICONS = {
  'icon-192.png': 'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAIAAADdvvtQAAAEpklEQVR42u3dyZHbMBAFUCWgFJSF8786HWfgg6s8ds1GiVh+N9+vuQ/U/SSSAAne7iInclMCAUgAEoAEIBGABCABSAASAUgAEoAEIBGABCAB6HEga/7LslQpWi6g9aXvAWgj2RRAu3pQGlDOL99OQHs7URRQ5gF0NaCEZlQEFH4etghQSEtqAapyLj8XUFRXCgEqd0k4BVBaY6oAKjqtMBhQYG9KACo9NTUMUGZ78gE1mN68NdDzWS3CAfWYIu8D6H0tkgG1WWO5tdED0BZDtzZ63tfCwBYY6gbo31oYVTSgR2oAWmmoIaC/tTCkXECP7FwN0M9fP779m2SoJ6A/tbjCeI7QOc5oEaBHhVwB0LN6ZhgCqOp4XtPzrSGALpEzer42BBBA2YA0r4GegYYAAgggegASgAQggAACCCCABCABCCCAAAIIIOkEiKHegKzGvxWi5XgAAujygNwT3RWQm+r/K0TLIQEEEECeTN03qnmAPJkKUClAdufYMrBJgOwPBNDrgGww9XEhWo6tGyB7JB5s8/vhHdzwYDag/Xsk3u3SeqDHH47wBUNjAZ1vfYd9onMAfdGtzwAd33tlOKAhfS+/U/0jZg/v17r1rKEoPXfvytgO6NljWZSe+4y39YToWQzofM8OGorScy/6vrCDZ385eg627YihHDpzAc3rX+Bv4djmTQI0qcvT35m6hU5pQF8PPofOIkBDehl+NjaviycBLejs6vfGL3DTCdD7zxLixmM9qwEN2UL14bkwgAASgAACCCCAAAIIIAEIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIoCI9Bgigs0UHCKCzFQcIoLPlBujqgBa0E6C2gJZ1FCCAAAKoe1MBAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIIIAAAggggAACCCCAAAIIoPKATuapWpz8X1FNHVW38u8LO+/mha/RZQGd/AXqAGjgj/ClAA08hFUFNOMQ/tQRuiigSedAxQDNOwE8fqJXDpD3xn/zBRrbzmaAll2FRQNafP3ZBtDiy/hQQLsmMEoD2jUPFAdo7wxYUUB7JxKDAG2fGgZo9iXtREAhawvlAIUsZWwGFLU4VQhQ1FoYQB8bigWUtpi6DVDg8jhAr32uDYBi768IBxR7OwdAANUBFH6HVyyg8BvKAAIIoEGbfwcCyr+ldRGg/JuUARo4HwsQQABd/v0VfQCVeM4GoIbPhQEEEEAAAQQQQAABBBBAAAEEEEAAAQQQQAABBBBAAM0HZDHVYipAAAHkfiCAALoooHuFzX7TBlmlaAC9FcKQcgGF1wKgNXp6AsocYaG6hW6uAFCJol0dUOzwCtUtdH+g9VUwttl6lm5xp0klinZdQLV+HZPrthpQQi3KHV6T67YB0N5aVDw/S67bHkC7alH0BD+5btsAra9F3SvE5LrtBLSyHKWnGGKLFgFodjkazFEl1y0C0Lxy9JjkjC1aFqCxFek0Sx5btERAJyvScpkluW6hgJ4tSqc1lmUfZ30r9wCSNgFIABKABCABSAQgAUgAEoBEABKABCABSAQgGZ3fR1wXiZJS1RQAAAAASUVORK5CYII=',
  'icon-512.png': 'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAIAAAB7GkOtAAASdElEQVR42u3d0bEeNRoE0D8BpzBZkP8r6ZABD65yGSjAd0YjqdWnaxPY/jR9dsG+9/NNREQq81GBiAgAREQEACIiAgAREQGAiIgAQEREACAiIgAQEREAiIgIAEREBAAiIgIAEREBgIiIAEBERAAgIiIAEBERAIiICABERAQAIiICABERAYCIiABAREQAICIiABARAYCIiABAREQAICIiABAREQCIiAgAREQEACIiAgAREQGAiIgAQEREACAiIgAQEREAiIgIAEREBAAiIgIAEREBQEauv6bqv6y8Hd+OAOCc1VOFeDAsBICZi3zTFhkAvh0AGP3SB22RvQrfDgDsfulrtsgeg28HAHa/9DVbZG9AbwCw+6VP2SK7vgIBYPpL37FFdnc1AsD0l75ji+ziygSA6S99xxbZrVUKANNf+o4tsisrFgDWv/QdW2T31S0ATH/pU7bILqthAJj+0nesZ2fVMwCsf+k71rCDqhoA1r/0HavXNbUNANNf+o5165Q6B4D1L33EinVHtQPA+pe+Y5W6oOYBYP1L37E+nU/5ALD+pe9YmW6nfwCY/tJ3rEmHcwUAWP/SR6xGV3MIAFj/0kesQydzCwBY/9JHrED3cg4AAKD0EWvPsZwDANa/9B2rzqVcBADWv/Qd682ZBADWv/QdK82NJM6Aj/UX4+JG0mnAx/rLkEesMQeSOAMAIGMesbpcRwBg/Uvfsa6cRuIM+Fh/sTJOI50GfKy/DHnEinIXiTMAADLmEWvJUQQA1t/WiKNIhgEAkDGPWEUuIgCw/qXvWD/OIXEGfKy/WBznkE4DACBjHrFy3EIAYP2NjriFZBgAABnziDXjEAIA6293xCEkwwAAyJhHrBZXEABYf9MjriAZBgBAxjxinTiBAMD6Wx9xgnfz+x+/vfefKgMAINbHCUz/VAYAAIDTBkgh+j9m/d9mAADW3wCJ/ved/hIDACBjHrE2lH/e+r/HAAAAYINE+QHr/4YBALD+NkiUHzD9BxsAABnziFWh+bPXf7gBAACAGRLNx6z/WAMAYDvMkGg+DICTDACAmCHNW/81BgDAdhyyRHpQe8/6jzIAALbDEona89YfANZfAKD2XgAOMAAAYonUbv2XGQAAOWGMlKDzwvUHAAAEADrvBeChAQAQYyS9naevPwCsvzFySp33ApBrAADEGOkcAAAAgABA59YfAAAQEQAAAAAiAgAAAEBEAAAAAIgIAAAAABEBAAAAICIAAAAARAQAALD+IgKAHQ0AgIgAAAAAEBEAAAAAIgIAAABARAAAAAaICAD8KSAAiAgAAAAAEQEAAAAgIgAAAABEBAAAAICIAAAAABARAAAAACfFKXUOAAAAwBiJzgEAAAAYI9E5AADAAGMkOgfAbusPADFGOgcAAAAgANA5AAAAALnxgvWgdgAAAACWSNQOAAAwwBKJ2gGw6/oDQCyR2gEAAADIsxesCs0DAAAAMEOieQAAgAFmSDQPgF3XHwAyZoNcUPkAAAAAbJAoHwAAYIANEuUDYOP1B4CMGSDn0z8AAAAAAyT6BwAAGGCARP8A2Hj9ASBj1sftnAAAAGCA9REnAEDG+gNAxkyPw7kCAADAANMjrgCAjPUHgIzZHVdzCAAAgAF2RxwCABnrDwAZMzpO5hYAAAADjI64BQAy1h8AMmZx3Ms5AAAABlgccQ4AZKw/AGTM3DiWiwAAAAwwN+IiAMhYfwDImK1xKUcBAAAYUDo0zuQuAIhb/wwAjIuhEQAkArD/tAJABqyMGzkNAADAgNKJcSDXAUDc+icBYGJMTFX+d3G+dJ0bv7MQAE8ASBnVJACszLbr7zTzN/GrB7r3q2sBcAOAoEUNA8DQ7Ln+7jJ/DW/c6PZvMAfArwOQNacAkDH/7FJvk3fw3plu/xpbAACAAdbfUXYZwduX2sqAwwCI29JIAMzNbuvvIvPn78mxbv8+WwD8BwCJQ5oKgMUBQPP6jwVgoQHHABC6osEAGJ191t8t5g/fw3ttYoD1B4DdiV9/h5i/es9PtoMB1h8Apid+/V1h/uQNudpyA6w/AKxP/Po7wfy9G3W4tQZYfwAYoOzp1/+SsRt7vlUGWH8A2KD49Vd+OgCr/n6A9QeAGYpff83PX7o3jjjfAOsPAGMUv/46nz9zL91xsgGmHwD2KH79FX4MAN/m/sw46w8Ak5Q9/dpesnFvH3SOAdYfAIYpfv31PH/gJtx0ggGmHwC2KXv6lXwqABMua/0BYKHi1x8ABwPw6nFNPwCMVPb0A2DJup1xYusPAFOVPf0AKAHgjUObfgAYrOzpB0AVAGPPbfoBYLaypx8AhQCMOrrpB4Dxyp5+ANQC8Pz0ph8AJMiefgCUA/DkAdh9AGAgePcBAIAnL8H0A4AEwbsPAAA8eRJ2HwAwCN59AADgydvQDwBgkDr6AADAw3eiEwBUk6ABAJSPnQZKATAQAoCI/6jo7YoAIAIAAAAAACIAAAAAACACAAAAAAAiAAAAAAAgAgAAAAAAIgAAAAAAIAIAAAAAACIAAAAAACACAAAAAAAiAAAAAAAgAgAAAAAAItYNAAAAgIh1AwAAACBi3QAAAACIWDcVAQAAItZNRQAAgIh1UxEAACBi3VQEAACIWDcVAQAAAgDrpiIAAEAAAAAVAQAAAgAAqAgAABAAAEBFABABAAAAAAARAAAAAAAQAQAAAAAAEQAAAAAAEAEAAAAAABEAAAAAABABAAAAAAARAAAAAAAQAQAAAAAAEQAAAAAAEAEAAAAAABEAAAAAABCxbgAAAABErBsAAAAAEesGAAAAQMS6qQgAABCxbioCAABErJuKAAAAEeumIgAAQMS6qQgAABAAAEBFAACAAAAAKgIAAMxizEJZNwAAAACS8bUDAAAAAID0/m9hAAAAAACQ6hEEAAAAAADpXUAAAAAAAJDq+dMAAAAAAOndPiUAAAAAkN7VUwUAAAAA6Z08bQAAAACQ3snTBgAAAADp/ZgVAgAAAEB6v2SdAAAAAJDSz1gtAAAAAKT3G9YMAAAAAOn9hjUDAAAAQEo/YOUAAAAAkN4PWDkAAAAApPTr1Q8AAAAA6f169QMAAABASj9dFQEAAAAQn66KVAQAAIhPV0UqAgAAxKerIhUBAADi01WRigAAAPHpqkhFAAAAAHy6KlIRAAAAAOumIhUBAAAAsG4qUhEAAAAA66YiFQEAAACwbipSEQAAAADrpiIVAUAAYN1UpCIACACsm4oAAAABgHVTEQAAIACwbioCAAAEANZNRQAAgADAuqkIAAAQAFg3FQEAAAIA66YiAABAAGDdVAQAAIhP17qpCAAAEJ+udVMRAAAgPl3rpiIAAEB8uipSEQAAID5dFakIAAAQn66KVAQAAIhPV0UqAgAAxKerIhUBAAAA8OmqSEUAAAAArJuKVAQAAADAuqlIRQAAAACsm4pUBAAAAMC6qUhFAAAAAKybilQEAAAAwLqpSEUAEABYNxUBAAACAOumIgAAQABg3VQEAAAIAKybigAAAAGAdVMRAAAgALBuKgIAAAQA1k1FAACAAMC6qQgAABAAWDcVAQAA4tO1bioCAADEp2vdVAQAAIhP17qpCAAAEJ+uilQEAACIT1dFKgIAAMSnqyIVAQAA4tNVkYoAAADx6apIRQAAAACsm4pUBAAAAMC6qUhFAAAAAKybilQEAAAAwLqpSEUAAAAArJuKVASAA3P7NR/TgHWbvG5ejtkBwC7/38WHDQAA3Ph2dAKA1NH3kQMAAA//Ya9+ABD5cCf/E0wAACDuSezz7wBMGQAGP9xV//4KAADY/CXs/C+BjRsAUqd/86cMgHIAgv4UkKEDQMz/Zkl5ygCoBSD3j4Gavo/pP+CPLQMAAHHT7/9MAyDs7W6+YgAAQND07/ZNAcD0Z/+VxbV/pRAAJQCc/TeBAWD6g//C+sK/WQ6A4wHo+VEQALD+kT+uZOEPGAHAwQAU/iwgAJj+yJ9XtcoAAJwKQPMPgwOA9T9h0QAAgCc3bf5poAAonf7on1U73wAAHAaAHwfdwMDH+pcA8DYDADgGAL8PoMeAj/U/9VdVTDYAAGcA4BfCVBnwMf1tALxkAAAOAMBvBGtj4GP9D/5NdTMNAEA6AH4lZKEBH+vfCcBwAwAQDYDfCdxpwMf61wIwlgEAhALgl8I3G/Cx/uUAjDIAAIkAnF0RA84HwLsc8t0CoBCA4ytiwOEAeJcDv1sAVAHQUBEDTgbgejOFADw0AABBAJRUxIBjAbheDgAAAAAABP1GpiIArvfTCcCTRwyAFAB6Kur5dUxFAFxTUgvA7UcMgAgAqioq+V1MAPAuB3+3ADgSgLaKAHAaANeslANw4x0DYHMACita9YoAkL3+ALjxjgGwMwCdFS18RQAIXn8AAAAAAHhYEQBS1x8ANx4xALYFoLai5a8IAACInzYARAPQXBEATgDgWhEAAAAAAHheEQDy1h8ANx6xljYEoLyiTV4RAAAQP20AiANARQDIBuBaFwAAAAAAGFURAAAQP20ACAJARQDIBuBaGgAAAAAAGFgRAAAQP20AiABARQDIBuBaHQAAAAAAGFsRAAAQP20A2BwAFQEgG4BrgwAAAAAAwPCKAACA+GkDwLYAqAgA2QBcewQAAAAAAN6oCAAAiJ82AGwIgIoAkA3AtU0AAAAAAOCligAAgOxp++cj1tJaAFQEgGwArp0CAAAAAADvVQQAAAAAAAAAAAAAEAjA3zZISwsBUBEAsgG4NgsAAAAAALxaEQAAAAAAAAAAAABAIAA/z5CWVgGgIgBkA3DtFwAAAAAAeLsiAAAAAAAAAAAAAIBAAH4skZaWAKAiAADAuwQAAFQEgEAAri0DAAAAAAATKgIAAAAAAAAAAAAACATg+xhpaT4AKgIAALxLAABARQAAgHcJAACoCAApAFy7BgAAAAAA5lQEAAAAAAAAAAAAAAAAAAAAAAAAQAoAWlKRigAAAABoSUUqAgAAAGDdVKQiAAAAANZNRSoCAAAAYN1UpCIAAAAA1k1FKgIAAABg3VQEgC4Aro3jUfp0VaSiaRUBAAAAsG4qAgAAAAAA66YiAAAAAACwbioCAAAAAADrpiIA+FNAAACAdVORPwUEAO8SANZNRQAAgHcJAOumIgAAwLsEgHVTEQAAAAAVWTcVAQAAAFCRdVMRAAAAABVZNxUBAAAAeF7RN78TePor+uZ3AgMAAN4lAACgIgAAwLsEAABUBIAcALY1wKMEAAAAMKGitfMLAAAAAAAAAAAAAAAAAAAAAAAAwK9X9P2OWpoPwLTafWgAAIBpAwAAfGgAKDAAAAAAAADermj59gIAAAAAAAAAAAAAfL2iH0fU0hIA5jTvQwMAAEwbAADgQwNAgQEAAAAAAPBqRTsMLwAAAAAAAAAAAADAFyv6+YJaWgXAhPJ9aADoMgAAAAAAAN6raJPVBYDcj/MpX0L/9S8AZOQLVoj+BQAMMECifwlYfwDIsBesEycQAADA+ogTCAAYYH3ECWTX9QeADHvBanEFAQADTI+4ggSsPwBk2AvWjEMIABhgd8QhJGD9ASDDXrBy3EIAwACjI24hAesPABn2gvXjHAIABlgccQ4JWP/dAfCOg16wilxEstYfADLsBWvJUQQADLA14igSsP4AkGEvWFHuIgBgQOnz1ZXTSNb6xwDgEVsZcRrr3wuAd7z5C1aX60jW+gNAhr1gjTmQAIABpc9XaW4kWeufB4BHbFzEjax/LwDe8Z4vWG/OJHFbGgmAd7zhC1adS7kIABhQ+oK151jOAQAAlL5gBbqXcwCAAaXPV4dO5hYAYEDp81WjqzkEABhQ+nw16XCuAAAMlD5fZbqd/gHAgNIXrE/nUz4AGFD6glXqgpoHAANKn69i3VHtAGBA6fPVrVPqHAAYKH2+6nVNbQOAAaUvWMMOqmoAMKD0+erZWfUMAAyUPl9L4bIaBgAGSp+vRXZf3QKAAaXP1yK7smIBgIHSt2uR3VqlAMBA6du1yC6uTABgoPTtWmR3VyMAMFD6di2y6ysQACQofbsW2RvQGwBIUPp2LbLH4NsBAAlK365F9ip8OwCAQenDtcimzbcDAB6UvlqLDADfDgDkX584C8Xq+XYAICIiABAREQCIiAgAREQEACIiAgAREQGAiIgAQEREACAiIgAQEREAiIgIAEREBAAiIgAQEREAiIgIAEREBAAiIgIAEREBgIiIAEBERAAgIiIAEBERAIiICABERAQAIiICABERAYCIiABAREQAICIiABAREQCIiAgAREQEACIiAgAREQGAiIgAQEREACAiAgAREQGAiIgAQEREjs2fOmKx2Wmljb0AAAAASUVORK5CYII='
};

function serveIcon(b64) {
  const binary = atob(b64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return new Response(bytes.buffer, {
    status: 200,
    headers: {
      'Content-Type': 'image/png',
      'Content-Length': bytes.length,
      'Cache-Control': 'public, max-age=86400'
    }
  });
}

const ASSETS = ['./', './index.html', './manifest.json'];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).catch(() => {}));
  self.skipWaiting();
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys =>
    Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
  ));
  self.clients.claim();
});

self.addEventListener('fetch', e => {
  const url = new URL(e.request.url);
  const filename = url.pathname.split('/').pop();

  // Serve icons with correct Content-Type
  if (ICONS[filename]) {
    e.respondWith(serveIcon(ICONS[filename]));
    return;
  }

  // Share target
  if (e.request.method === 'POST') {
    e.respondWith((async () => {
      const data = await e.request.formData().catch(() => null);
      if (data) {
        const file = data.get('file');
        const clients = await self.clients.matchAll();
        if (clients[0] && file) clients[0].postMessage({ type: 'shared-file', file });
      }
      return Response.redirect(url.pathname, 303);
    })());
    return;
  }

  // Cache first
  e.respondWith(
    caches.match(e.request).then(cached => {
      if (cached) return cached;
      return fetch(e.request).then(res => {
        if (res && res.status === 200 && e.request.method === 'GET') {
          caches.open(CACHE).then(c => c.put(e.request, res.clone()));
        }
        return res;
      }).catch(() => cached || new Response('Offline', { status: 503 }));
    })
  );
});
